-- Safely add evaluation columns to existing PRESENTATION table if they don't already exist
ALTER TABLE PRESENTATION ADD COLUMN IF NOT EXISTS SCI_KNOWLEDGE INT DEFAULT 0;
ALTER TABLE PRESENTATION ADD COLUMN IF NOT EXISTS REPRESENTATION_ACCURACY INT DEFAULT 0;
ALTER TABLE PRESENTATION ADD COLUMN IF NOT EXISTS PUBLIC_SPEAKING INT DEFAULT 0;
ALTER TABLE PRESENTATION ADD COLUMN IF NOT EXISTS PARTICIPATION INT DEFAULT 0;
ALTER TABLE PRESENTATION ADD COLUMN IF NOT EXISTS RESOLUTION_DRAFTING INT DEFAULT 0;
ALTER TABLE PRESENTATION ADD COLUMN IF NOT EXISTS COLLABORATION INT DEFAULT 0;
ALTER TABLE PRESENTATION ADD COLUMN IF NOT EXISTS LEADERSHIP_MATRIX INT DEFAULT 0;

-- Add session_id column to link delegates to specific sessions
ALTER TABLE PRESENTATION ADD COLUMN IF NOT EXISTS SESSION_ID BIGINT;
